# Generated by Django 2.1 on 2018-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20180821_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='way_to_root',
            field=models.TextField(blank=True),
        ),
    ]
