# Generated by Django 2.1 on 2018-08-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_way_to_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='way_to_root',
            field=models.TextField(blank=True, null=True),
        ),
    ]
