# Generated by Django 2.1 on 2018-08-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20180827_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='way_to_root',
        ),
        migrations.AddField(
            model_name='node',
            name='relation',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='relation_info',
            field=models.TextField(blank=True, max_length=127),
        ),
    ]
