# Generated by Django 2.1 on 2018-08-27 00:32

from django.db import migrations
from nodes import default_data

class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_auto_20180827_1155'),
    ]

    operations = [
        migrations.RunPython(default_data.default_nodes),
    ]
